---
ID: "29534f60-9266-44a9-8ad4-3362972a2aae"
Parent: "c0943942-ae0f-4205-86fa-84884cce4a53"
Template: "c0943942-ae0f-4205-86fa-84884cce4a53"
Path: /sitecore/templates/Project/Financial/Components/Promo CTA/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A5BC37E7-ED96-4C1E-8590-A26E64DB55EA}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c78f25a8-1a1d-43cd-bcef-f52d6172489e"
- ID: "e495efd3-5c43-45fc-af43-796a6b503716"
  Hint: Image
  Value: |
    <image mediaid="{FC78C30D-DE27-4D68-AEF8-A4F389FEEA4D}" alt="close-up-young-businesswoman" height="" width="" hspace="" vspace="" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1f82a687-0683-426f-b12a-4b2100a6a481"
      Hint: Title
      Value: Lorem ipsum dolor sit amet
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260905T111550Z
    - ID: "2fbad11a-8129-4c7e-aacc-6973619327a1"
      Hint: Eyebrow
      Value: suscipit lectus
    - ID: "32f3e9b1-c441-4285-a063-0897453f37e2"
      Hint: Link2
      Value: |
        <link text="More Details" linktype="external" url="https://example.com" anchor="" target="" />
    - ID: "507ba267-78fc-42f1-ac96-a1cb769b6de6"
      Hint: Link
      Value: |
        <link text="Details" linktype="external" url="https://example.com" anchor="" target="" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0696d268-1913-43be-a7d0-24451b43ed34"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "cc0cb595-ce5c-413e-b413-3a7176347f28"
      Hint: Text
      Value: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260905T111550Z
    - ID: "e4f11fe1-3b24-42e4-8cea-9ed7fda32bab"
      Hint: Subtitle
      Value: Maecenas nec rhoncus risus.
